vim.keymap.set("n", "<leader>lp", function()
	vim.diagnostic.jump({ count = -1, float = true })
end, { desc = "[L]sp [P]revious diagnostic message" })
vim.keymap.set("n", "<leader>ln", function()
	vim.diagnostic.jump({ count = 1, float = true })
end, { desc = "[L]sp [N]ext diagnostic message" })
vim.keymap.set("n", "<leader>lo", vim.diagnostic.open_float, { desc = "[L]sp [O]pen error messages" })
vim.keymap.set("n", "<leader>q", vim.diagnostic.setloclist, { desc = "Open diagnostic [Q]uickfix list" })
vim.keymap.set("n", "<leader>lf", vim.lsp.buf.format, { desc = "[F]ormat with [L]sp" })

vim.keymap.set("n", "<leader>bn", vim.cmd.bnext, { desc = "[B]uffer [N]ext" })
vim.keymap.set("n", "<leader>bp", vim.cmd.bprev, { desc = "[B]uffer [P]revious" })
vim.keymap.set("n", "<leader>bd", vim.cmd.bdelete, { desc = "[B]uffer [D]elete" })
vim.keymap.set("n", "<leader>bl", vim.cmd.blast, { desc = "[B] [L]ast buffer" })
